### ISSUE TITLE
Soft bootloop on 12L

### ISSUE THREAD

**Issue by StarkDroid** [B--B/xiaomi_msm8996-common#3] opened 2022-03-14 06:03 UTC
So I tried booting my rom after a fresh merge of 12.1 and took some logs. Here by soft bootloop i mean that the entire bootanimation completes, right at the moment where it should go into system it starts a bootloop. Thought you might be able to look into the logs and see if anything interests you.

This was being spammed at the end of console-ramoops
`init: Control message: Could not find 'android.frameworks.sensorservice@1.0::ISensorManager/default' &or ctl.interface_start from 0id: 588 (/system/bin/hwservicemanager)`

Got a sepolicy denial, Although not sure if its something i haven't added in source side
`init: File /vendor/bin/hw/vendor.lineage.touch@1.0-service.xiaomi_8996 (labeled "u:object_r:vendor_file:s0") has incorrect label or no domain transition from u:r:init:s0 to another SELinux domain defined. Have you configured your service correctly? https://source.android.com/security/selinux/device-policy#label_new_services_and_address_denials. Note: this error shows up even in permissive mode in order to make auditing denials possible.`

couple of more denials taken from In-boot progress logcat and more can be found in the attached logcat but either ways, since we are running it permissive, it shouldn't be an issue:
`E SELinux : avc:  denied  { add } for interface=android.hardware.power.stats::IPowerStats sid=u:r:init:s0 pid=874 scontext=u:r:init:s0 tcontext=u:object_r:hal_power_stats_hwservice:s0 tclass=hwservice_manager permissive=1`
`E SELinux : avc:  denied  { find } for interface=vendor.lineage.touch::IKeyDisabler sid=u:r:init:s0 pid=885 scontext=u:r:init:s0 tcontext=u:object_r:hal_lineage_touch_hwservice:s0 tclass=hwservice_manager permissive=1`

Here's a complete boot progress logcat
[https://www.toptal.com/developers/hastebin/ipuyadebup.yaml](url)

**Comment by B--B** [comment] 2022-03-21 16:53
Hi there, sorry for being so late, i'm busy with work in these days and i lost your message.. BTW i saw that yesterday Pixel Experience updated their sources to Android 12.1, i'm syncing right now, will let you know in a few hours if works here. Regarding the logs, i just took a quick look and i noticed that there's a couple of libs missing but should not break the boot (already added locally, if everything works fine i will push them), the bootloop seems caused by phone app, but it isn't the root cause. Did you check if RIL is working properly? you can take a look with "adb logcat -b radio", because IMS is crashing too, don't think it's working, and may cause the phone app crash

PS: yes, you can forget about selinux denials for now, until we are in permissive mode all selinux denials are just logs :)

**Comment by B--B** [comment] 2022-03-21 20:24
Dirty flashed over Android 12 and everything works fine here, also all OMX related errors are all gone, let me know if bootloops for you.
 PS: soundtrigger removal is not well tested, keep in mind that could cause mic issues, if you find something wrong please send me a report

**Comment by StarkDroid** [comment] 2022-03-22 07:26
I'll give it a run today and see what comes up, thanks for getting back! Will let you know how it goes.

**Comment by B--B** [comment] 2022-03-29 15:48
If you merge my latest changes take a look at [this change](https://github.com/B--B/xiaomi_msm8996-common/commit/c42d7ccb39d0b5e18209d1c5fdf75e022531fbbe#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42L130), your ROM must support the USE_DEVICE_SPECIFIC_ flag or the default qcom-caf/msm8996 path will be used.

**Comment by StarkDroid** [comment] 2022-03-30 21:04
> If you merge my latest changes take a look at [this change](https://github.com/B--B/xiaomi_msm8996-common/commit/c42d7ccb39d0b5e18209d1c5fdf75e022531fbbe#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42L130), your ROM must support the USE_DEVICE_SPECIFIC_ flag or the default qcom-caf/msm8996 path will be used.

This is great, now i can continue testing further! Boots up all good. Appreciate the work, thanks!!

**Comment by B--B** [comment] 2022-04-02 11:30
I'm glad that finally works! :) I close this issue, feel free to open a new one if you experience other problems!

PS: latest code merge in kernel introduced a bug, i've reset last days history and merged only the safe fixes in inline branch, sync your branch with mine otherwise you'll experience random tasks crashing!

**Closed as completed by B--B** 2022-04-02 11:30 UTC
